"""One-shot splitter. Reads tool_definitions.py, slices each tool dict by AST,
writes per-domain modules, and rewrites tool_definitions.py as an aggregator."""

import ast
import textwrap
from pathlib import Path

SRC = Path(__file__).parent / "tool_definitions.py"
DOMAINS_DIR = Path(__file__).parent / "domains"

DOMAIN_MAP = {
    "search_azure_docs": "qa",
    "compare_services": "comparison",
    "recommend_service": "comparison",
    "compare_regions": "comparison",
    "design_architecture": "architecture",
    "generate_adr": "architecture",
    "design_network_topology": "network",
    "design_landing_zone": "governance",
    "assess_waf_pillar": "waf",
    "generate_bicep": "bicep",
    "generate_code_files": "codegen",
    "estimate_costs": "cost",
    "generate_tco_report": "cost",
    "generate_monitoring_config": "monitoring",
    "map_compliance": "compliance",
    "assess_migration": "migration",
    "design_dr_strategy": "drbc",
    "generate_deck_outline": "presentation",
    "review_deck_outline": "presentation",
    "generate_learning_plan": "learning",
    "generate_practice_exam": "learning",
    "design_rbac_model": "security",
    "generate_threat_register": "security",
    "design_pipeline": "devsecops",
    "define_slo_framework": "monitoring",
    "recommend_sku": "sizing",
    "create_stakeholder_plan": "stakeholder",
    "generate_project_timeline": "project",
    "diagnose_issue": "troubleshoot",
    "generate_kql_queries": "troubleshoot",
    "generate_remediation_runbook": "troubleshoot",
    "validate_resource_naming": "governance",
    "suggest_resource_name": "governance",
}

source = SRC.read_text(encoding="utf-8")
tree = ast.parse(source)

# Collect dict literals from TOOLS = [...] AND TOOLS.extend([...]) calls
tool_elements: list[ast.AST] = []
for node in tree.body:
    if isinstance(node, ast.Assign) and any(
        isinstance(t, ast.Name) and t.id == "TOOLS" for t in node.targets
    ) and isinstance(node.value, ast.List):
        tool_elements.extend(node.value.elts)
    elif isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
        call = node.value
        if (
            isinstance(call.func, ast.Attribute)
            and isinstance(call.func.value, ast.Name)
            and call.func.value.id == "TOOLS"
            and call.func.attr == "extend"
            and call.args
            and isinstance(call.args[0], ast.List)
        ):
            tool_elements.extend(call.args[0].elts)

assert tool_elements, "No TOOLS entries found"

src_lines = source.splitlines(keepends=True)

def slice_node(n: ast.AST) -> str:
    lines = src_lines[n.lineno - 1 : n.end_lineno]
    text = "".join(lines)
    text = textwrap.dedent(text).rstrip()
    if text.endswith(","):
        text = text[:-1].rstrip()
    return text

domain_tools: dict[str, list[tuple[str, str]]] = {}
for elem in tool_elements:
    # Each elem is a dict literal with "function": {"name": "..."}
    name = None
    if isinstance(elem, ast.Dict):
        for k, v in zip(elem.keys, elem.values):
            if isinstance(k, ast.Constant) and k.value == "function" and isinstance(v, ast.Dict):
                for fk, fv in zip(v.keys, v.values):
                    if isinstance(fk, ast.Constant) and fk.value == "name" and isinstance(fv, ast.Constant):
                        name = fv.value
                        break
                break
    if not name:
        continue
    domain = DOMAIN_MAP.get(name, "qa")
    domain_tools.setdefault(domain, []).append((name, slice_node(elem)))

DOMAINS_DIR.mkdir(exist_ok=True)
(DOMAINS_DIR / "__init__.py").write_text("", encoding="utf-8")

domain_names = sorted(domain_tools.keys())
for domain in domain_names:
    body_parts = [s for _, s in domain_tools[domain]]
    content = f'"""Auto-generated by _split.py — {domain} tool schemas."""\n\nTOOLS = [\n'
    content += ",\n".join(textwrap.indent(p, "    ") for p in body_parts)
    content += ",\n]\n"
    (DOMAINS_DIR / f"{domain}.py").write_text(content, encoding="utf-8")

# Build aggregator (preserves public surface: TOOLS, TOOLS_BY_MODE, get_tools_for_mode)
agg = ['"""Aggregator. Tool schemas live in tools/domains/*.py."""', ""]
for d in domain_names:
    agg.append(f"from tools.domains.{d} import TOOLS as _{d}_tools")
agg.append("")
agg.append("TOOLS = " + " + ".join(f"_{d}_tools" for d in domain_names))
agg.append("")
agg.append('_BY_NAME = {t["function"]["name"]: t for t in TOOLS}')
agg.append("")
agg.append("def get_tools(*names: str) -> list:")
agg.append("    return [_BY_NAME[n] for n in names if n in _BY_NAME]")
agg.append("")

# Carry over TOOLS_BY_MODE + _MCP_ENABLED_MODES + get_tools_for_mode verbatim
marker = "TOOLS_BY_MODE: dict[str, list] = {"
idx = source.find(marker)
assert idx != -1
tail = source[idx:]
agg.append(tail)

SRC.write_text("\n".join(agg), encoding="utf-8")

print(f"Wrote {len(domain_names)} domain modules:")
for d in domain_names:
    print(f"  {d}.py: {len(domain_tools[d])} tools")
print(f"Total tools: {sum(len(v) for v in domain_tools.values())}")
