"""Auto-generated by _split.py — architecture tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "design_architecture",
            "description": (
                "Generate a structured Azure architecture design. Returns a list of components "
                "(Azure services) and connections between them, plus a design overview. "
                "Call this for any architecture design or 'how would I build X on Azure' request."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "requirements": {
                        "type": "string",
                        "description": "Workload description — what the system needs to do.",
                    },
                    "constraints": {
                        "type": "string",
                        "description": "Compliance, region, budget, latency, or other constraints.",
                    },
                    "pattern": {
                        "type": "string",
                        "enum": [
                            "hub-spoke", "microservices", "event-driven",
                            "batch", "web-app", "saas-multitenant", "custom",
                        ],
                        "description": "Primary architectural pattern.",
                    },
                    "components": {
                        "type": "array",
                        "description": "List of Azure service components to include.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string"},
                                "label": {"type": "string", "description": "Display name"},
                                "shape": {
                                    "type": "string",
                                    "description": "draw.io azure2 shape key, e.g. application_gateway, aks, cosmos_db",
                                },
                                "category": {
                                    "type": "string",
                                    "enum": ["networking", "compute", "data", "security", "monitoring", "default"],
                                },
                                "tier": {
                                    "type": "integer",
                                    "description": "Layout tier 0=internet/users, 1=edge/gateway, 2=app, 3=data, 4=monitoring/security",
                                },
                                "group": {
                                    "type": "string",
                                    "enum": ["external", "edge", "compute", "data", "observability"],
                                    "description": (
                                        "Cluster bucket for diagram layout. external=users/internet/3rd-party SaaS; "
                                        "edge=Front Door/App Gateway/WAF/API Mgmt/DNS; "
                                        "compute=App Service/AKS/Container Apps/Functions/VMs; "
                                        "data=SQL/Cosmos/Storage/Redis/Key Vault/Service Bus; "
                                        "observability=Monitor/App Insights/Log Analytics/Sentinel. "
                                        "Populate this for every component — components with the same group "
                                        "are drawn together in a dashed cluster box, which dramatically "
                                        "reduces edge crossings on dense diagrams."
                                    ),
                                },
                            },
                            "required": ["id", "label", "shape", "group"],
                        },
                    },
                    "connections": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "from": {"type": "string"},
                                "to": {"type": "string"},
                                "label": {"type": "string"},
                            },
                            "required": ["from", "to"],
                        },
                    },
                    "overview": {
                        "type": "string",
                        "description": "1-2 sentence description of the architecture for the runbook.",
                    },
                    "deployment_steps": {
                        "type": "array",
                        "description": (
                            "Ordered deployment phases with service-specific Azure CLI commands. "
                            "Include real az CLI commands, resource names, and SKU flags for each service."
                        ),
                        "items": {
                            "type": "object",
                            "properties": {
                                "phase": {"type": "string", "description": "Phase name, e.g. 'Phase 1 — Networking'"},
                                "service": {"type": "string", "description": "Azure service being deployed"},
                                "description": {"type": "string"},
                                "commands": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Azure CLI or Bicep commands to deploy this service",
                                },
                            },
                            "required": ["phase", "service", "commands"],
                        },
                    },
                },
                "required": ["requirements", "components", "connections", "overview"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_adr",
            "description": (
                "Generate an Architecture Decision Record (ADR) documenting the primary architectural "
                "choice made during the design. Captures context, the decision made, trade-offs, "
                "and alternatives considered. Call this when the user requested an ADR output."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Short title for the ADR, e.g. 'Use Azure Container Apps over AKS for stateless microservices'.",
                    },
                    "status": {
                        "type": "string",
                        "enum": ["Proposed", "Accepted", "Deprecated"],
                    },
                    "context": {
                        "type": "string",
                        "description": "The architectural problem or question being addressed, including constraints and business drivers.",
                    },
                    "decision": {
                        "type": "string",
                        "description": "What was decided and the primary rationale.",
                    },
                    "consequences": {
                        "type": "string",
                        "description": "What becomes easier or harder as a result. Include positive outcomes and trade-offs.",
                    },
                    "alternatives": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Alternative options that were considered but rejected, with brief reason.",
                    },
                },
                "required": ["title", "status", "context", "decision", "consequences"],
            },
        },
    },
]
