"""Auto-generated by _split.py — bicep tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "generate_bicep",
            "description": (
                "Generate Azure Bicep (IaC) templates for a given architecture or specific Azure resources. "
                "Returns ready-to-deploy Bicep code with parameter files and deployment instructions."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "resources": {
                        "type": "array",
                        "description": "List of Azure resources to generate Bicep for.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {"type": "string", "description": "Azure resource type, e.g. Microsoft.Web/sites"},
                                "name": {"type": "string", "description": "Logical resource name"},
                                "sku": {"type": "string", "description": "SKU/tier if applicable"},
                                "properties": {"type": "object", "description": "Key resource properties"},
                            },
                            "required": ["type", "name"],
                        },
                    },
                    "bicep_code": {
                        "type": "string",
                        "description": "Complete Bicep template code as a string.",
                    },
                    "param_file": {
                        "type": "string",
                        "description": "Bicep parameter file (.bicepparam) content.",
                    },
                    "deploy_commands": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Azure CLI commands to deploy the template.",
                    },
                    "target_scope": {
                        "type": "string",
                        "enum": ["resourceGroup", "subscription", "managementGroup"],
                        "description": (
                            "Bicep targetScope. Use 'resourceGroup' (default) for most PaaS/IaaS resources "
                            "(App Service, SQL, AKS, Key Vault, Storage, etc.). "
                            "Use 'subscription' for resource groups, subscription-level role assignments, "
                            "Azure Policy assignments, and Cost Management budgets. "
                            "Use 'managementGroup' only for org-wide policy initiatives. "
                            "Always choose the narrowest scope that satisfies the deployment requirements."
                        ),
                    },
                    "notes": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Important notes, prerequisites, or customization guidance.",
                    },
                },
                "required": ["bicep_code", "target_scope"],
            },
        },
    },
]
