"""Auto-generated by _split.py — codegen tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "generate_code_files",
            "description": (
                "Generate complete, production-ready code files for the described requirements. "
                "Return all files needed to run the project, including configuration, tests, and README."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "files": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string",
                                    "description": "Relative file path, e.g. 'src/main.py' or 'README.md'.",
                                },
                                "content": {"type": "string", "description": "Complete file content."},
                                "language": {
                                    "type": "string",
                                    "description": "Language for syntax highlighting, e.g. 'python', 'typescript'.",
                                },
                                "description": {
                                    "type": "string",
                                    "description": "One-line description of what this file does.",
                                },
                            },
                            "required": ["name", "content", "language"],
                        },
                    },
                    "repo_name": {
                        "type": "string",
                        "description": "Suggested GitHub repository name (kebab-case, no spaces).",
                    },
                    "summary": {
                        "type": "string",
                        "description": "1-2 sentence summary of what was generated and how to run it.",
                    },
                },
                "required": ["files", "repo_name", "summary"],
            },
        },
    },
]
