"""Auto-generated by _split.py — comparison tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "compare_services",
            "description": (
                "Output a structured side-by-side comparison of 2-4 Azure services. "
                "Call this tool INSTEAD OF writing a text comparison table. "
                "The 'values' object in each row MUST use the exact same service name strings "
                "as the 'services' array — keys that don't match will show as blank cells."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "services": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Exact display names of the services, e.g. ['Azure Service Bus', 'Azure Event Hubs', 'Azure Event Grid']. These same strings must be keys in every values object.",
                    },
                    "use_case": {
                        "type": "string",
                        "description": "The workload or scenario driving the comparison.",
                    },
                    "comparison_rows": {
                        "type": "array",
                        "description": "6-8 comparison rows. Each row's 'values' keys MUST exactly match the strings in 'services'.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "dimension": {"type": "string", "description": "Row label, e.g. 'Primary use case fit'"},
                                "values": {
                                    "type": "object",
                                    "description": "Keys are the EXACT service name strings from the 'services' array. Values are 1-2 sentence descriptions.",
                                    "additionalProperties": {"type": "string"},
                                },
                            },
                            "required": ["dimension", "values"],
                        },
                    },
                    "recommendation": {
                        "type": "string",
                        "description": "Overall recommendation with 'choose X when...' guidance for each service.",
                    },
                    "decision_tree": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Decision criteria: 'if [condition] → choose [service]'.",
                    },
                },
                "required": ["services", "comparison_rows", "recommendation"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "compare_regions",
            "description": (
                "Output a structured comparison of 2-6 Azure regions for a given workload. "
                "Compare across key dimensions: AZ count, data residency, paired region, latency tier, "
                "compliance certifications, service availability, and cost delta. "
                "Call this for any multi-region selection or region recommendation request."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "regions": {
                        "type": "array",
                        "description": "Azure regions to compare.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "region_name": {"type": "string", "description": "Azure region display name, e.g. East US"},
                                "geography": {"type": "string", "description": "Geographic area, e.g. United States, Europe, Asia Pacific"},
                                "az_count": {"type": "integer", "description": "Number of Availability Zones (0 if none)"},
                                "data_residency": {"type": "string", "description": "Data residency boundary, e.g. United States, EU, Germany"},
                                "paired_region": {"type": "string", "description": "Azure paired region name"},
                                "latency_tier": {"type": "string", "description": "Relative latency tier for the workload, e.g. Low (<20ms), Medium (20-80ms), High (>80ms)"},
                                "cost_delta": {"type": "string", "description": "Cost relative to East US baseline, e.g. Baseline, +5%, -3%"},
                                "compliance_certs": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Key compliance certifications available in this region, e.g. FedRAMP High, HIPAA, PCI-DSS",
                                },
                                "key_services_available": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Workload-relevant Azure services confirmed available in this region",
                                },
                            },
                            "required": ["region_name", "geography", "az_count", "data_residency", "paired_region", "latency_tier", "cost_delta", "compliance_certs", "key_services_available"],
                        },
                    },
                    "recommendation": {
                        "type": "string",
                        "description": "Overall recommendation — which region(s) to use and why, with 'choose X when...' guidance.",
                    },
                    "notes": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Additional notes on region selection trade-offs or constraints.",
                    },
                },
                "required": ["regions", "recommendation"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "recommend_service",
            "description": (
                "Output a structured service or approach recommendation when the user asks which Azure service to use, "
                "which approach to take, or 'what do you recommend?' "
                "Call this INSTEAD of a text recommendation to produce a scannable decision card with rationale, trade-offs, and guardrails."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "recommendation": {
                        "type": "string",
                        "description": "The primary recommendation in one sentence.",
                    },
                    "rationale": {
                        "type": "string",
                        "description": "2-3 sentence rationale explaining why this is the right choice for the stated requirements.",
                    },
                    "tradeoffs": {
                        "type": "array",
                        "description": "Key trade-offs to be aware of.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "aspect": {"type": "string", "description": "Trade-off dimension, e.g. Cost, Operational complexity, Scalability"},
                                "detail": {"type": "string", "description": "1-2 sentence description of the trade-off."},
                            },
                            "required": ["aspect", "detail"],
                        },
                    },
                    "when_to_reconsider": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Conditions under which this recommendation no longer applies.",
                    },
                },
                "required": ["recommendation", "rationale", "tradeoffs", "when_to_reconsider"],
            },
        },
    },
]
