"""Auto-generated by _split.py — compliance tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "map_compliance",
            "description": (
                "Map an Azure architecture or set of services to specific compliance framework "
                "requirements. Identifies gaps, required controls, and Azure-native compliance tools."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "framework": {
                        "type": "string",
                        "enum": ["HIPAA", "PCI-DSS", "SOC2", "FedRAMP", "GDPR", "ISO27001", "NIST-CSF", "CIS-Azure"],
                        "description": "Compliance framework to map against.",
                    },
                    "architecture_description": {
                        "type": "string",
                        "description": "Description of the architecture or services in scope.",
                    },
                    "controls_met": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of framework controls that are satisfied.",
                    },
                    "gaps": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "control": {"type": "string"},
                                "gap": {"type": "string"},
                                "remediation": {"type": "string"},
                                "azure_service": {"type": "string"},
                            },
                            "required": ["control", "gap", "remediation"],
                        },
                        "description": "Controls not met and how to remediate.",
                    },
                    "azure_policy_recommendations": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Recommended Azure Policy definitions or initiatives to enable.",
                    },
                    "shared_responsibility_notes": {
                        "type": "string",
                        "description": "What Microsoft is responsible for vs. what the customer must handle.",
                    },
                },
                "required": ["framework", "architecture_description", "controls_met", "gaps"],
            },
        },
    },
]
