"""Auto-generated by _split.py — cost tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "estimate_costs",
            "description": (
                "Estimate monthly Azure costs for a set of services using the local Azure Retail "
                "pricing catalog (resolved via a deterministic fuzzy SKU matcher, with the live "
                "Retail API as fallback). Each line item returns the resolved/matched SKU, a "
                "confidence score, and the alternative SKUs considered. Present the matched SKU and "
                "confidence to the user; when confidence is low or the matched SKU differs from what "
                "was requested, say so and ask them to confirm rather than quoting the number as fact."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "line_items": {
                        "type": "array",
                        "description": "Services to estimate costs for.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string", "description": "Azure service name, e.g. Azure App Service"},
                                "sku": {"type": "string", "description": "SKU/tier, e.g. P2v3, Standard"},
                                "quantity": {"type": "number", "description": "Number of instances or units"},
                                "hours_per_month": {"type": "number", "description": "Running hours per month (default 730)"},
                                "region": {"type": "string", "description": "Azure region, e.g. eastus"},
                            },
                            "required": ["service"],
                        },
                    },
                    "optimization_tips": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Cost optimization recommendations for the estimated workload.",
                    },
                },
                "required": ["line_items"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_tco_report",
            "description": (
                "Generate a structured Total Cost of Ownership (TCO) report comparing "
                "on-premises infrastructure to Azure. Include itemised costs, 3-year totals, "
                "migration costs, break-even timeline, and recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "on_prem_items": {
                        "type": "array",
                        "description": "On-premises cost line items.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "category": {"type": "string", "description": "e.g. Hardware, Software, Facilities, Staff"},
                                "description": {"type": "string"},
                                "annual_cost": {"type": "number", "description": "Annual USD cost"},
                            },
                            "required": ["category", "description", "annual_cost"],
                        },
                    },
                    "azure_items": {
                        "type": "array",
                        "description": "Azure service cost line items.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string", "description": "Azure service name"},
                                "sku": {"type": "string", "description": "SKU / tier / size"},
                                "monthly_cost": {"type": "number", "description": "Monthly USD cost"},
                            },
                            "required": ["service", "sku", "monthly_cost"],
                        },
                    },
                    "three_year_on_prem_total": {
                        "type": "number",
                        "description": "Total 3-year on-prem cost in USD.",
                    },
                    "three_year_azure_total": {
                        "type": "number",
                        "description": "Total 3-year Azure cost in USD (including migration).",
                    },
                    "migration_cost_estimate": {
                        "type": "number",
                        "description": "One-time migration cost estimate in USD.",
                    },
                    "break_even_months": {
                        "type": "number",
                        "description": "Months until Azure investment breaks even vs on-prem.",
                    },
                    "savings_percentage": {
                        "type": "number",
                        "description": "3-year cost savings as a percentage.",
                    },
                    "recommendations": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Prioritised recommendations to maximise TCO savings.",
                    },
                },
                "required": [
                    "on_prem_items", "azure_items",
                    "three_year_on_prem_total", "three_year_azure_total", "recommendations",
                ],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "live_price_lookup",
            "description": (
                "Resolve the Azure Retail price for one SKU right now via the local pricing catalog "
                "and deterministic resolver (live Retail API as fallback). Use when the user asks "
                "'what does X cost today?' rather than for full architecture costing. Returns the "
                "matched SKU, confidence, and candidate alternatives — surface the matched SKU and "
                "confidence, and confirm with the user when confidence is low instead of inventing a price."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "service": {"type": "string", "description": "Azure service name, e.g. 'Virtual Machines'."},
                    "sku": {"type": "string", "description": "SKU/tier, e.g. 'D8s_v5'."},
                    "region": {"type": "string", "description": "Azure region, e.g. 'eastus'."},
                    "quantity": {"type": "number", "description": "Number of units, default 1."},
                    "hours_per_month": {"type": "number", "description": "Running hours/month, default 730."},
                },
                "required": ["service"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "analyze_reservations",
            "description": (
                "Pull live RI / savings-plan recommendations from Azure Consumption for the engagement "
                "subscription and rank them by payback. Use for 'should we reserve?' questions."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "subscription_id": {"type": "string", "description": "Subscription GUID; falls back to default when omitted."},
                    "scope": {"type": "string", "enum": ["Single", "Shared"], "description": "RI scope: Single subscription or Shared billing account."},
                    "lookback_days": {"type": "integer", "enum": [7, 30, 60], "description": "Usage history window for the recommendation."},
                },
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "recommend_rightsizing",
            "description": (
                "Walk every VM in the subscription, pull last-N-day P95 CPU from Azure Monitor, "
                "and recommend a smaller SKU when sustained utilisation is below the threshold."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "subscription_id": {"type": "string", "description": "Subscription GUID; falls back to default."},
                    "window_days": {"type": "integer", "description": "Lookback window in days (default 14)."},
                    "threshold_pct": {"type": "number", "description": "P95 CPU% threshold below which to recommend a downsize (default 40)."},
                },
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "estimate_carbon",
            "description": (
                "Order-of-magnitude monthly kg CO2e for a list of compute line items. "
                "Optionally compare against other candidate regions to pick the greenest."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "line_items": {
                        "type": "array",
                        "description": "Compute line items: service, sku, region, quantity, hours_per_month.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string"},
                                "sku": {"type": "string"},
                                "region": {"type": "string"},
                                "quantity": {"type": "number"},
                                "hours_per_month": {"type": "number"},
                            },
                            "required": ["service"],
                        },
                    },
                    "compare_regions": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Optional regions to re-evaluate the same workload against.",
                    },
                },
                "required": ["line_items"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "price_services",
            "description": (
                "Price one or more Azure services across ALL their billing meters (not just compute "
                "hours) using the live Azure Retail Pricing API. Use this for the Pricing Desk worksheet "
                "whenever the user wants a structured, exportable price for any Azure service — storage, "
                "databases, networking, AI, bandwidth, etc. Each line is priced through the meter-aware "
                "catalog (e.g. SQL = vCore + storage + backup; Storage = capacity tiers + operations) with "
                "a universal single-meter fallback for uncatalogued services. Returns a per-line meter "
                "breakdown that populates the right-hand worksheet."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "line_items": {
                        "type": "array",
                        "description": "Services to price. Pass dimensions for non-hourly meters (e.g. storage GB, operations).",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string", "description": "Azure service name, e.g. 'Storage', 'SQL Database', 'Azure Cosmos DB'."},
                                "sku": {"type": "string", "description": "SKU / tier, e.g. 'D8s_v5', 'Hot LRS', 'General Purpose'."},
                                "quantity": {"type": "number", "description": "Instance/unit count (default 1)."},
                                "hours_per_month": {"type": "number", "description": "Running hours/month for hourly meters (default 730)."},
                                "region": {"type": "string", "description": "Azure region, e.g. 'eastus'."},
                                "display_name": {"type": "string", "description": "Friendly label for the worksheet row."},
                                "dimensions": {
                                    "type": "object",
                                    "description": "Named non-hourly quantities the catalog meter expects, e.g. {\"storage_gb\": 5000, \"write_ops\": 1000000}.",
                                    "additionalProperties": {"type": "number"},
                                },
                            },
                            "required": ["service"],
                        },
                    },
                    "optimization_tips": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Cost-savings recommendations for this worksheet (RIs, region swap, right-sizing, tier change).",
                    },
                    "currency": {"type": "string", "description": "ISO currency code (default USD)."},
                },
                "required": ["line_items"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "check_region_availability",
            "description": (
                "For one Azure service + SKU, report where it is available and the live unit price in each "
                "candidate Azure region, cheapest first. Use when the user asks 'where can I run this?' or "
                "'is there a cheaper region?'. Populates the region-availability strip in the Pricing Desk."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "service": {"type": "string", "description": "Azure service name, e.g. 'Virtual Machines'."},
                    "sku": {"type": "string", "description": "SKU/tier to check, e.g. 'D8s_v5'."},
                    "regions": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Optional explicit region list; defaults to a curated global set.",
                    },
                    "currency": {"type": "string", "description": "ISO currency code (default USD)."},
                },
                "required": ["service"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "compare_payg_vs_ri",
            "description": (
                "Pure-math comparator: given PAYG monthly, reserved monthly, optional upfront, and term, "
                "return break-even months, total term savings, and a Reserve/PAYG recommendation."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "payg_monthly": {"type": "number", "description": "Pay-as-you-go monthly cost in USD."},
                    "reserved_monthly": {"type": "number", "description": "Effective monthly cost under the reservation."},
                    "upfront_cost": {"type": "number", "description": "Upfront payment, default 0 for monthly billing."},
                    "term_years": {"type": "integer", "enum": [1, 3], "description": "Reservation term in years."},
                },
                "required": ["payg_monthly", "reserved_monthly"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "suggest_alternatives",
            "description": (
                "Given ONE priced compute SKU, return functionally-equivalent, typically-cheaper "
                "alternatives (e.g. Intel D-series -> AMD Das-series), each priced live and ranked "
                "cheapest-first with the monthly delta vs the baseline and the tradeoff to verify. "
                "Call this after pricing a VM so the customer sees concrete cheaper options instead of "
                "a single number. Suggestions are drawn from a grounded equivalence map — if no known "
                "alternative exists for the SKU the list is empty (do not invent one)."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "service": {"type": "string", "description": "Azure service name, e.g. 'Virtual Machines'."},
                    "sku": {"type": "string", "description": "Baseline SKU to find alternatives for, e.g. 'D8s_v5'."},
                    "region": {"type": "string", "description": "Azure region, e.g. 'eastus' (default eastus)."},
                    "quantity": {"type": "number", "description": "Number of instances (default 1)."},
                    "hours_per_month": {"type": "number", "description": "Running hours/month (default 730)."},
                },
                "required": ["service", "sku"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "request_clarification",
            "description": (
                "Ask the user targeted disambiguation questions BEFORE pricing or designing when the "
                "request is too vague to produce a trustworthy number — e.g. 'a database' without engine "
                "type, no size/SKU, or no region. Present 1-4 concise questions, each with concrete "
                "options the user can pick. Do NOT guess defaults for required disambiguators; call this "
                "instead and wait for the answers. Re-call with only the still-missing questions if the "
                "user answers partially."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "questions": {
                        "type": "array",
                        "description": "The disambiguation questions to ask, most important first.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "question": {"type": "string", "description": "The question to ask the user."},
                                "options": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Concrete answer choices the user can pick (quick replies).",
                                },
                                "why_it_matters": {
                                    "type": "string",
                                    "description": "One sentence on why this changes the price or design.",
                                },
                                "allow_free_text": {
                                    "type": "boolean",
                                    "description": "Whether the user may answer outside the listed options (default true).",
                                },
                            },
                            "required": ["question"],
                        },
                    },
                    "known_so_far": {
                        "type": "object",
                        "description": "The partial spec already understood (service, sku, region, quantity, etc.) so it is carried forward.",
                        "additionalProperties": True,
                    },
                    "context": {
                        "type": "string",
                        "description": "Optional one-line framing shown above the questions.",
                    },
                },
                "required": ["questions"],
            },
        },
    },
]
