"""Auto-generated by _split.py — cost tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "estimate_costs",
            "description": (
                "Estimate monthly Azure costs for a set of services using the Azure Retail Pricing API. "
                "Returns line-item cost estimates with optimization recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "line_items": {
                        "type": "array",
                        "description": "Services to estimate costs for.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string", "description": "Azure service name, e.g. Azure App Service"},
                                "sku": {"type": "string", "description": "SKU/tier, e.g. P2v3, Standard"},
                                "quantity": {"type": "number", "description": "Number of instances or units"},
                                "hours_per_month": {"type": "number", "description": "Running hours per month (default 730)"},
                                "region": {"type": "string", "description": "Azure region, e.g. eastus"},
                            },
                            "required": ["service"],
                        },
                    },
                    "optimization_tips": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Cost optimization recommendations for the estimated workload.",
                    },
                },
                "required": ["line_items"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_tco_report",
            "description": (
                "Generate a structured Total Cost of Ownership (TCO) report comparing "
                "on-premises infrastructure to Azure. Include itemised costs, 3-year totals, "
                "migration costs, break-even timeline, and recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "on_prem_items": {
                        "type": "array",
                        "description": "On-premises cost line items.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "category": {"type": "string", "description": "e.g. Hardware, Software, Facilities, Staff"},
                                "description": {"type": "string"},
                                "annual_cost": {"type": "number", "description": "Annual USD cost"},
                            },
                            "required": ["category", "description", "annual_cost"],
                        },
                    },
                    "azure_items": {
                        "type": "array",
                        "description": "Azure service cost line items.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string", "description": "Azure service name"},
                                "sku": {"type": "string", "description": "SKU / tier / size"},
                                "monthly_cost": {"type": "number", "description": "Monthly USD cost"},
                            },
                            "required": ["service", "sku", "monthly_cost"],
                        },
                    },
                    "three_year_on_prem_total": {
                        "type": "number",
                        "description": "Total 3-year on-prem cost in USD.",
                    },
                    "three_year_azure_total": {
                        "type": "number",
                        "description": "Total 3-year Azure cost in USD (including migration).",
                    },
                    "migration_cost_estimate": {
                        "type": "number",
                        "description": "One-time migration cost estimate in USD.",
                    },
                    "break_even_months": {
                        "type": "number",
                        "description": "Months until Azure investment breaks even vs on-prem.",
                    },
                    "savings_percentage": {
                        "type": "number",
                        "description": "3-year cost savings as a percentage.",
                    },
                    "recommendations": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Prioritised recommendations to maximise TCO savings.",
                    },
                },
                "required": [
                    "on_prem_items", "azure_items",
                    "three_year_on_prem_total", "three_year_azure_total", "recommendations",
                ],
            },
        },
    },
]
