"""Auto-generated by _split.py — cost tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "estimate_costs",
            "description": (
                "Estimate monthly Azure costs for a set of services using the Azure Retail Pricing API. "
                "Returns line-item cost estimates with optimization recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "line_items": {
                        "type": "array",
                        "description": "Services to estimate costs for.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string", "description": "Azure service name, e.g. Azure App Service"},
                                "sku": {"type": "string", "description": "SKU/tier, e.g. P2v3, Standard"},
                                "quantity": {"type": "number", "description": "Number of instances or units"},
                                "hours_per_month": {"type": "number", "description": "Running hours per month (default 730)"},
                                "region": {"type": "string", "description": "Azure region, e.g. eastus"},
                            },
                            "required": ["service"],
                        },
                    },
                    "optimization_tips": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Cost optimization recommendations for the estimated workload.",
                    },
                },
                "required": ["line_items"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_tco_report",
            "description": (
                "Generate a structured Total Cost of Ownership (TCO) report comparing "
                "on-premises infrastructure to Azure. Include itemised costs, 3-year totals, "
                "migration costs, break-even timeline, and recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "on_prem_items": {
                        "type": "array",
                        "description": "On-premises cost line items.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "category": {"type": "string", "description": "e.g. Hardware, Software, Facilities, Staff"},
                                "description": {"type": "string"},
                                "annual_cost": {"type": "number", "description": "Annual USD cost"},
                            },
                            "required": ["category", "description", "annual_cost"],
                        },
                    },
                    "azure_items": {
                        "type": "array",
                        "description": "Azure service cost line items.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string", "description": "Azure service name"},
                                "sku": {"type": "string", "description": "SKU / tier / size"},
                                "monthly_cost": {"type": "number", "description": "Monthly USD cost"},
                            },
                            "required": ["service", "sku", "monthly_cost"],
                        },
                    },
                    "three_year_on_prem_total": {
                        "type": "number",
                        "description": "Total 3-year on-prem cost in USD.",
                    },
                    "three_year_azure_total": {
                        "type": "number",
                        "description": "Total 3-year Azure cost in USD (including migration).",
                    },
                    "migration_cost_estimate": {
                        "type": "number",
                        "description": "One-time migration cost estimate in USD.",
                    },
                    "break_even_months": {
                        "type": "number",
                        "description": "Months until Azure investment breaks even vs on-prem.",
                    },
                    "savings_percentage": {
                        "type": "number",
                        "description": "3-year cost savings as a percentage.",
                    },
                    "recommendations": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Prioritised recommendations to maximise TCO savings.",
                    },
                },
                "required": [
                    "on_prem_items", "azure_items",
                    "three_year_on_prem_total", "three_year_azure_total", "recommendations",
                ],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "live_price_lookup",
            "description": (
                "Resolve the live Azure Retail price for one SKU right now. "
                "Use when the user asks 'what does X cost today?' rather than for full architecture costing."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "service": {"type": "string", "description": "Azure service name, e.g. 'Virtual Machines'."},
                    "sku": {"type": "string", "description": "SKU/tier, e.g. 'D8s_v5'."},
                    "region": {"type": "string", "description": "Azure region, e.g. 'eastus'."},
                    "quantity": {"type": "number", "description": "Number of units, default 1."},
                    "hours_per_month": {"type": "number", "description": "Running hours/month, default 730."},
                },
                "required": ["service"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "analyze_reservations",
            "description": (
                "Pull live RI / savings-plan recommendations from Azure Consumption for the engagement "
                "subscription and rank them by payback. Use for 'should we reserve?' questions."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "subscription_id": {"type": "string", "description": "Subscription GUID; falls back to default when omitted."},
                    "scope": {"type": "string", "enum": ["Single", "Shared"], "description": "RI scope: Single subscription or Shared billing account."},
                    "lookback_days": {"type": "integer", "enum": [7, 30, 60], "description": "Usage history window for the recommendation."},
                },
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "recommend_rightsizing",
            "description": (
                "Walk every VM in the subscription, pull last-N-day P95 CPU from Azure Monitor, "
                "and recommend a smaller SKU when sustained utilisation is below the threshold."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "subscription_id": {"type": "string", "description": "Subscription GUID; falls back to default."},
                    "window_days": {"type": "integer", "description": "Lookback window in days (default 14)."},
                    "threshold_pct": {"type": "number", "description": "P95 CPU% threshold below which to recommend a downsize (default 40)."},
                },
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "estimate_carbon",
            "description": (
                "Order-of-magnitude monthly kg CO2e for a list of compute line items. "
                "Optionally compare against other candidate regions to pick the greenest."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "line_items": {
                        "type": "array",
                        "description": "Compute line items: service, sku, region, quantity, hours_per_month.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string"},
                                "sku": {"type": "string"},
                                "region": {"type": "string"},
                                "quantity": {"type": "number"},
                                "hours_per_month": {"type": "number"},
                            },
                            "required": ["service"],
                        },
                    },
                    "compare_regions": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Optional regions to re-evaluate the same workload against.",
                    },
                },
                "required": ["line_items"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "compare_payg_vs_ri",
            "description": (
                "Pure-math comparator: given PAYG monthly, reserved monthly, optional upfront, and term, "
                "return break-even months, total term savings, and a Reserve/PAYG recommendation."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "payg_monthly": {"type": "number", "description": "Pay-as-you-go monthly cost in USD."},
                    "reserved_monthly": {"type": "number", "description": "Effective monthly cost under the reservation."},
                    "upfront_cost": {"type": "number", "description": "Upfront payment, default 0 for monthly billing."},
                    "term_years": {"type": "integer", "enum": [1, 3], "description": "Reservation term in years."},
                },
                "required": ["payg_monthly", "reserved_monthly"],
            },
        },
    },
]
