"""Auto-generated by _split.py — devsecops tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "design_pipeline",
            "description": (
                "Design a DevSecOps CI/CD pipeline with security gates, supply chain security, "
                "and workload identity. Returns pipeline stages, security scans, and identity configuration."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "platform": {
                        "type": "string",
                        "enum": ["github-actions", "azure-devops", "both"],
                    },
                    "branch_strategy": {
                        "type": "string",
                        "description": "Branching strategy (e.g. trunk-based, GitFlow, GitHub flow).",
                    },
                    "stages": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "jobs": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {"type": "string"},
                                            "is_security_gate": {"type": "boolean"},
                                            "steps": {"type": "array", "items": {"type": "string"}},
                                        },
                                        "required": ["name", "is_security_gate"],
                                    },
                                },
                            },
                            "required": ["name", "jobs"],
                        },
                    },
                    "security_scans": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {"type": "string", "enum": ["SAST", "DAST", "SCA", "IaC", "Container"]},
                                "tool": {"type": "string"},
                                "blocking": {"type": "boolean"},
                            },
                            "required": ["type", "tool", "blocking"],
                        },
                    },
                    "workload_identity": {
                        "type": "string",
                        "description": "Workload identity federation configuration for the pipeline.",
                    },
                    "secrets_management": {
                        "type": "string",
                        "description": "How secrets are managed (e.g. Azure Key Vault + OIDC, GitHub encrypted secrets).",
                    },
                },
                "required": ["platform", "branch_strategy", "stages", "security_scans", "workload_identity", "secrets_management"],
            },
        },
    },
]
