"""Auto-generated by _split.py — drbc tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "design_dr_strategy",
            "description": (
                "Design a disaster recovery and business continuity strategy for an Azure workload. "
                "Returns DR pattern recommendation, service-specific configurations, and a test plan."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "workload_description": {"type": "string"},
                    "rto_hours": {
                        "type": "number",
                        "description": "Required Recovery Time Objective in hours.",
                    },
                    "rpo_hours": {
                        "type": "number",
                        "description": "Required Recovery Point Objective in hours.",
                    },
                    "dr_pattern": {
                        "type": "string",
                        "enum": ["hot-standby", "warm-standby", "cold-standby", "pilot-light", "multi-region-active"],
                        "description": "Recommended DR pattern.",
                    },
                    "primary_region": {"type": "string"},
                    "secondary_region": {"type": "string"},
                    "service_configs": {
                        "type": "array",
                        "description": "Per-service DR configuration.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "service": {"type": "string"},
                                "dr_approach": {"type": "string"},
                                "rpo_achieved": {"type": "string"},
                                "azure_feature": {"type": "string"},
                            },
                            "required": ["service", "dr_approach"],
                        },
                    },
                    "failover_steps": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Step-by-step failover procedure.",
                    },
                    "test_plan": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "DR test procedures and recommended cadence.",
                    },
                    "estimated_monthly_dr_cost": {
                        "type": "string",
                        "description": "Rough cost estimate for the DR infrastructure.",
                    },
                },
                "required": ["workload_description", "dr_pattern", "service_configs", "failover_steps"],
            },
        },
    },
]
