"""Auto-generated by _split.py — governance tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "design_landing_zone",
            "description": (
                "Design an Azure Landing Zone following Cloud Adoption Framework (CAF) principles. "
                "Returns management group hierarchy, policy initiatives, naming convention, "
                "mandatory tags, RBAC assignments, and subscription vending approach."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "management_groups": {
                        "type": "array",
                        "description": "Management group tree (flat list with parent_id for hierarchy).",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "level": {"type": "integer", "description": "0=root, 1=platform, 2=workload, etc."},
                                "parent_id": {"type": "string"},
                            },
                            "required": ["name", "level"],
                        },
                    },
                    "policy_initiatives": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Policy initiative names to assign (e.g. 'Azure Security Benchmark', 'CIS Azure Foundations').",
                    },
                    "naming_convention": {
                        "type": "string",
                        "description": "CAF naming pattern with example (e.g. '<abbrev>-<workload>-<env>-<region>-<instance>').",
                    },
                    "mandatory_tags": {
                        "type": "object",
                        "additionalProperties": {"type": "string"},
                        "description": "Tag name → allowed values or description.",
                    },
                    "rbac_assignments": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "principal": {"type": "string"},
                                "role": {"type": "string"},
                                "scope": {"type": "string"},
                            },
                            "required": ["principal", "role", "scope"],
                        },
                    },
                    "subscription_vending": {
                        "type": "string",
                        "description": "Subscription vending automation approach and tooling.",
                    },
                },
                "required": ["management_groups", "policy_initiatives", "naming_convention", "mandatory_tags", "rbac_assignments"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "validate_resource_naming",
            "description": (
                "Validate proposed Azure resource names against the Cloud Adoption Framework "
                "(abbreviation + workload + env + region) plus per-type length/character rules. "
                "Returns per-name pass/fail, errors, warnings, and a suggested fix."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "items": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "resource_type": {"type": "string", "description": "CAF key, e.g. 'storageAccount', 'keyVault'."},
                                "name": {"type": "string"},
                            },
                            "required": ["resource_type", "name"],
                        },
                    },
                },
                "required": ["items"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "suggest_resource_name",
            "description": (
                "Produce a CAF-conformant Azure resource name from workload + env + region inputs."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "resource_type": {"type": "string"},
                    "workload": {"type": "string"},
                    "env": {"type": "string", "default": "dev"},
                    "region": {"type": "string", "default": "eastus2"},
                    "suffix": {"type": "string"},
                },
                "required": ["resource_type", "workload"],
            },
        },
    },
]
