"""Auto-generated by _split.py — learning tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "generate_learning_plan",
            "description": (
                "Generate a structured learning plan with half-day modules, learning outcomes, "
                "prerequisite skills, and topic breakdowns with skills taught per session."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {
                        "type": "string",
                        "description": "Descriptive title for the learning plan.",
                    },
                    "overview": {
                        "type": "string",
                        "description": "2-3 sentence summary of what the plan covers and who it is for.",
                    },
                    "target_audience": {
                        "type": "string",
                        "description": "Role and experience level of the intended learners.",
                    },
                    "duration_days": {
                        "type": "number",
                        "description": "Total duration in days (0.5 increments, max 3).",
                    },
                    "prerequisites": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Specific prerequisite skills or certifications required.",
                    },
                    "learning_outcomes": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Measurable outcomes learners will achieve (verb + object).",
                    },
                    "modules": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "session_label": {
                                    "type": "string",
                                    "description": "e.g. 'Day 1 - Morning' or 'Half Day - Morning'",
                                },
                                "title": {"type": "string"},
                                "duration_hours": {"type": "number"},
                                "description": {
                                    "type": "string",
                                    "description": "Brief explanation of the session focus and approach.",
                                },
                                "topics": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Ordered list of topics covered in this session.",
                                },
                                "skills_taught": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Observable skills learners will demonstrate after this session.",
                                },
                                "activities": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Labs, demos, discussions, or case studies.",
                                },
                            },
                            "required": ["session_label", "title", "description", "topics", "skills_taught"],
                        },
                    },
                },
                "required": ["title", "overview", "target_audience", "duration_days", "prerequisites", "learning_outcomes", "modules"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_practice_exam",
            "description": (
                "Generate a structured practice exam pack with multiple-choice questions in the style of the target Azure certification. "
                "Each question has 4 choices (A-D), the correct answer, a detailed explanation, and the exam domain. "
                "Call this INSTEAD of writing questions as plain text whenever the user asks for practice questions, a quiz, or exam prep material."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "exam": {
                        "type": "string",
                        "description": "Target exam code and name, e.g. AZ-305: Azure Solutions Architect Expert",
                    },
                    "questions": {
                        "type": "array",
                        "description": "Practice questions.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "question": {"type": "string", "description": "Full scenario-based question text as it would appear on the exam."},
                                "choices": {
                                    "type": "object",
                                    "properties": {
                                        "A": {"type": "string"},
                                        "B": {"type": "string"},
                                        "C": {"type": "string"},
                                        "D": {"type": "string"},
                                    },
                                    "required": ["A", "B", "C", "D"],
                                },
                                "correct": {
                                    "type": "string",
                                    "enum": ["A", "B", "C", "D"],
                                    "description": "Letter of the correct answer.",
                                },
                                "explanation": {
                                    "type": "string",
                                    "description": "Detailed explanation of why the correct answer is right and why the distractors are wrong.",
                                },
                                "domain": {
                                    "type": "string",
                                    "description": "Exam domain/skill area this question tests, e.g. Design Data Storage Solutions",
                                },
                            },
                            "required": ["question", "choices", "correct", "explanation", "domain"],
                        },
                    },
                },
                "required": ["exam", "questions"],
            },
        },
    },
]
