"""Auto-generated by _split.py — migration tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "assess_migration",
            "description": (
                "Assess a workload for cloud migration using the 6 R's framework "
                "(Rehost, Replatform, Refactor, Repurchase, Retain, Retire). "
                "Returns recommended migration strategy with effort, risk, and wave planning."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "workload_name": {"type": "string"},
                    "current_state": {
                        "type": "string",
                        "description": "Current infrastructure, OS, database, application stack.",
                    },
                    "strategy": {
                        "type": "string",
                        "enum": ["Rehost", "Replatform", "Refactor", "Repurchase", "Retain", "Retire"],
                    },
                    "rationale": {"type": "string"},
                    "target_azure_services": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Azure services that replace the current stack.",
                    },
                    "effort_weeks": {
                        "type": "integer",
                        "description": "Estimated migration effort in weeks.",
                    },
                    "risk_level": {
                        "type": "string",
                        "enum": ["Low", "Medium", "High", "Critical"],
                    },
                    "wave": {
                        "type": "integer",
                        "description": "Suggested migration wave number (1 = first to migrate).",
                    },
                    "key_steps": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "High-level migration steps.",
                    },
                    "blockers": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Known blockers or dependencies that must be resolved first.",
                    },
                },
                "required": ["workload_name", "current_state", "strategy", "rationale", "target_azure_services", "risk_level"],
            },
        },
    },
]
