"""Auto-generated by _split.py — monitoring tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "generate_monitoring_config",
            "description": (
                "Generate Azure Monitor alert rules, KQL queries, and Log Analytics configurations "
                "for a described architecture or set of services."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "alert_rules": {
                        "type": "array",
                        "description": "Azure Monitor alert rule definitions.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "resource_type": {"type": "string"},
                                "metric_or_kql": {"type": "string", "description": "Metric name or KQL query"},
                                "threshold": {"type": "string"},
                                "severity": {"type": "integer", "minimum": 0, "maximum": 4},
                                "description": {"type": "string"},
                            },
                            "required": ["name", "metric_or_kql", "threshold", "severity"],
                        },
                    },
                    "kql_queries": {
                        "type": "array",
                        "description": "Useful KQL queries for dashboards and investigations.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "query": {"type": "string"},
                                "description": {"type": "string"},
                            },
                            "required": ["name", "query"],
                        },
                    },
                    "dashboard_widgets": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Recommended Azure Monitor dashboard tiles/workbook sections.",
                    },
                    "bicep_alerts": {
                        "type": "string",
                        "description": "Optional Bicep code to deploy the alert rules.",
                    },
                },
                "required": ["alert_rules"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "define_slo_framework",
            "description": (
                "Define SLOs, SLIs, error budgets, and multi-window burn rate alerts for an Azure workload. "
                "Returns per-service SLOs, composite SLA, burn rate alert definitions, and chaos experiment recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "services": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "azure_sla": {"type": "string", "description": "Microsoft's published SLA (e.g. 99.95%)"},
                                "customer_slo": {"type": "string", "description": "Customer-facing SLO (e.g. 99.9%)"},
                                "sli_definition": {"type": "string", "description": "How the SLI is measured (metric or KQL)"},
                                "error_budget_minutes": {"type": "number", "description": "Monthly error budget in minutes"},
                            },
                            "required": ["name", "azure_sla", "customer_slo", "sli_definition", "error_budget_minutes"],
                        },
                    },
                    "composite_sla": {
                        "type": "string",
                        "description": "End-to-end composite SLA calculation with formula.",
                    },
                    "error_budget_alerts": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "window": {"type": "string", "description": "e.g. '1 hour (fast burn)' or '6 hours (slow burn)'"},
                                "burn_rate": {"type": "number", "description": "Burn rate multiplier (e.g. 14.4 for fast burn)"},
                                "description": {"type": "string"},
                            },
                            "required": ["window", "burn_rate", "description"],
                        },
                    },
                    "toil_inventory": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Identified toil items (repetitive manual operational tasks).",
                    },
                    "chaos_experiments": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Recommended Azure Chaos Studio experiments.",
                    },
                },
                "required": ["services", "composite_sla", "error_budget_alerts", "toil_inventory", "chaos_experiments"],
            },
        },
    },
]
