"""Auto-generated by _split.py — network tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "design_network_topology",
            "description": (
                "Design an Azure network topology including VNets, subnets, NSG rules, "
                "private endpoints, DNS design, and firewall configuration. "
                "Call this for any hub-spoke, vWAN, or network security design request."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "topology_type": {
                        "type": "string",
                        "enum": ["hub-spoke", "vwan", "single-vnet", "peered"],
                        "description": "Primary topology pattern.",
                    },
                    "vnets": {
                        "type": "array",
                        "description": "VNet definitions with subnets.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "cidr": {"type": "string", "description": "e.g. 10.0.0.0/16"},
                                "region": {"type": "string"},
                                "subnets": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {"type": "string"},
                                            "cidr": {"type": "string"},
                                            "purpose": {"type": "string"},
                                        },
                                        "required": ["name", "cidr"],
                                    },
                                },
                            },
                            "required": ["name", "cidr", "subnets"],
                        },
                    },
                    "nsg_rules": {
                        "type": "array",
                        "description": "Key NSG rules to highlight.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "priority": {"type": "integer"},
                                "direction": {"type": "string", "enum": ["Inbound", "Outbound"]},
                                "action": {"type": "string", "enum": ["Allow", "Deny"]},
                                "source": {"type": "string"},
                                "destination": {"type": "string"},
                                "port": {"type": "string"},
                                "protocol": {"type": "string"},
                            },
                            "required": ["name", "priority", "direction", "action", "source", "destination", "port", "protocol"],
                        },
                    },
                    "private_endpoints": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "resource": {"type": "string"},
                                "subnet": {"type": "string"},
                                "private_dns_zone": {"type": "string"},
                            },
                            "required": ["resource", "subnet", "private_dns_zone"],
                        },
                    },
                    "dns_design": {
                        "type": "string",
                        "description": "DNS resolution strategy (e.g. Azure Private DNS Resolver for hybrid split-horizon).",
                    },
                    "firewall": {
                        "type": "string",
                        "description": "Azure Firewall configuration summary (tier, key rule collections).",
                    },
                },
                "required": ["topology_type", "vnets", "nsg_rules", "private_endpoints"],
            },
        },
    },
]
