"""Auto-generated by _split.py — presentation tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "generate_deck_outline",
            "description": (
                "Generate a complete slide-by-slide deck outline for a customer-facing presentation. "
                "Returns a structured outline with varied layouts, content bullets, and speaker notes. "
                "Always include a title slide, agenda slide, section dividers, summary, and references slide."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "deck_title": {"type": "string"},
                    "subtitle": {"type": "string"},
                    "slides": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "slide_number": {"type": "integer"},
                                "layout": {
                                    "type": "string",
                                    "enum": [
                                        "title", "agenda", "section_divider",
                                        "content", "two_column", "quote_stat",
                                        "summary", "references",
                                    ],
                                },
                                "title": {"type": "string"},
                                "content": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": (
                                        "Bullet points for content/summary/agenda/references layouts. "
                                        "For quote_stat: first item is the big stat/quote, second is a supporting fact. "
                                        "For title: first item is the subtitle text."
                                    ),
                                },
                                "right_content": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "Right-column bullets for two_column layout only.",
                                },
                                "speaker_notes": {
                                    "type": "string",
                                    "description": "Full speaker notes for presenting this slide.",
                                },
                            },
                            "required": ["slide_number", "layout", "title", "content", "speaker_notes"],
                        },
                    },
                },
                "required": ["deck_title", "subtitle", "slides"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "review_deck_outline",
            "description": (
                "Review a presentation deck outline and return structured recommendations "
                "plus a fully improved version of the outline incorporating those recommendations."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "overall_assessment": {
                        "type": "string",
                        "description": "2-3 sentence overall quality assessment of the outline.",
                    },
                    "recommendations": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "type": {
                                    "type": "string",
                                    "enum": ["structure", "content", "narrative", "audience_fit"],
                                },
                                "issue": {"type": "string", "description": "What the problem is."},
                                "suggestion": {"type": "string", "description": "How to fix it."},
                                "severity": {"type": "string", "enum": ["high", "medium", "low"]},
                            },
                            "required": ["type", "issue", "suggestion", "severity"],
                        },
                    },
                    "improved_outline": {
                        "type": "object",
                        "description": "A fully revised outline that incorporates all recommendations.",
                        "properties": {
                            "deck_title": {"type": "string"},
                            "subtitle": {"type": "string"},
                            "slides": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "slide_number": {"type": "integer"},
                                        "layout": {"type": "string"},
                                        "title": {"type": "string"},
                                        "content": {"type": "array", "items": {"type": "string"}},
                                        "right_content": {"type": "array", "items": {"type": "string"}},
                                        "speaker_notes": {"type": "string"},
                                    },
                                    "required": ["slide_number", "layout", "title", "content", "speaker_notes"],
                                },
                            },
                        },
                        "required": ["deck_title", "subtitle", "slides"],
                    },
                },
                "required": ["overall_assessment", "recommendations", "improved_outline"],
            },
        },
    },
]
