"""Auto-generated by _split.py — project tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "generate_project_timeline",
            "description": (
                "Produce a realistic phased implementation timeline (Gantt) for an Azure project. "
                "Use for architecture, migration, DR, and landing-zone planning."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "phases": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string", "description": "Phase name, e.g. 'Network Foundation'"},
                                "start_week": {"type": "integer", "minimum": 0},
                                "duration_weeks": {"type": "integer", "minimum": 1},
                                "dependencies": {"type": "array", "items": {"type": "string"}},
                                "deliverables": {"type": "array", "items": {"type": "string"}},
                            },
                            "required": ["name", "start_week", "duration_weeks"],
                        },
                    },
                    "total_weeks": {"type": "integer", "minimum": 1},
                    "critical_path": {"type": "array", "items": {"type": "string"}},
                    "notes": {"type": "string"},
                },
                "required": ["phases", "total_weeks"],
            },
        },
    },
]
