"""Auto-generated by _split.py — qa tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "search_azure_docs",
            "description": (
                "Search Microsoft Learn and Azure documentation for authoritative answers. "
                "Always call this before answering any Azure technical question. "
                "Returns article titles, URLs, and summaries."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Specific search query targeting the Azure topic.",
                    },
                    "category": {
                        "type": "string",
                        "enum": [
                            "architecture", "security", "cost", "reliability",
                            "networking", "storage", "compute", "identity", "",
                        ],
                        "description": "Optional category filter. Leave empty for broad search.",
                    },
                },
                "required": ["query"],
            },
        },
    },
]
