"""Auto-generated by _split.py — security tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "design_rbac_model",
            "description": (
                "Design an Entra ID identity and RBAC model including role assignments, PIM, "
                "Conditional Access policies, managed identities, and workload identity federation."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "principals": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "List of principals (groups, service principals, managed identities).",
                    },
                    "role_assignments": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "principal": {"type": "string"},
                                "role": {"type": "string"},
                                "scope": {"type": "string"},
                                "type": {"type": "string", "enum": ["Active", "PIM-Eligible"]},
                            },
                            "required": ["principal", "role", "scope", "type"],
                        },
                    },
                    "custom_roles": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "permissions": {"type": "array", "items": {"type": "string"}},
                            },
                            "required": ["name", "permissions"],
                        },
                    },
                    "conditional_access_policies": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string"},
                                "conditions": {"type": "string"},
                                "grant_controls": {"type": "string"},
                            },
                            "required": ["name", "conditions", "grant_controls"],
                        },
                    },
                    "pim_settings": {
                        "type": "string",
                        "description": "PIM activation settings (MFA, approval, max duration).",
                    },
                    "workload_federation": {
                        "type": "string",
                        "description": "Workload identity federation configuration (e.g. GitHub Actions OIDC → Entra ID).",
                    },
                },
                "required": ["principals", "role_assignments", "custom_roles", "conditional_access_policies"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_threat_register",
            "description": (
                "Generate a STRIDE threat register for an Azure architecture. "
                "Returns trust boundaries, attack surface, threats with risk scores, "
                "and recommended security controls."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "trust_boundaries": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Trust boundary definitions (e.g. 'Internet → API Gateway', 'App → Database').",
                    },
                    "attack_surface": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Exposed attack surface items.",
                    },
                    "threats": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string", "description": "e.g. T-001"},
                                "title": {"type": "string"},
                                "stride_category": {
                                    "type": "string",
                                    "enum": ["Spoofing", "Tampering", "Repudiation", "Information Disclosure", "Denial of Service", "Elevation of Privilege"],
                                },
                                "likelihood": {"type": "integer", "minimum": 1, "maximum": 5},
                                "impact": {"type": "integer", "minimum": 1, "maximum": 5},
                                "risk_score": {"type": "integer", "minimum": 1, "maximum": 25, "description": "likelihood × impact"},
                                "mitigations": {"type": "array", "items": {"type": "string"}},
                                "azure_controls": {"type": "array", "items": {"type": "string"}},
                                "status": {"type": "string", "enum": ["Open", "Mitigated", "Accepted"]},
                            },
                            "required": ["id", "title", "stride_category", "likelihood", "impact", "risk_score", "mitigations", "azure_controls", "status"],
                        },
                    },
                    "security_controls_recommended": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Overall recommended security controls.",
                    },
                },
                "required": ["trust_boundaries", "attack_surface", "threats", "security_controls_recommended"],
            },
        },
    },
]
