"""Auto-generated by _split.py — sizing tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "recommend_sku",
            "description": (
                "Recommend Azure SKUs for each component of an architecture based on workload profile. "
                "Returns SKU recommendations with alternatives and autoscale configuration."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "workload_profile": {
                        "type": "object",
                        "properties": {
                            "peak_users": {"type": "integer"},
                            "avg_rps": {"type": "number"},
                            "data_volume_gb": {"type": "number"},
                            "latency_p99_ms": {"type": "number"},
                            "availability_target": {"type": "string"},
                        },
                    },
                    "recommendations": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "component": {"type": "string"},
                                "recommended_sku": {"type": "string"},
                                "vcpu": {"type": "number"},
                                "memory_gb": {"type": "number"},
                                "reasoning": {"type": "string"},
                                "utilization_target": {"type": "string"},
                                "alternatives": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "sku": {"type": "string"},
                                            "trade_off": {"type": "string"},
                                            "monthly_delta": {"type": "number", "description": "Cost delta vs recommended (negative=cheaper)"},
                                        },
                                        "required": ["sku", "trade_off", "monthly_delta"],
                                    },
                                },
                                "autoscale": {
                                    "type": "object",
                                    "properties": {
                                        "min": {"type": "integer"},
                                        "max": {"type": "integer"},
                                        "scale_trigger": {"type": "string"},
                                    },
                                },
                            },
                            "required": ["component", "recommended_sku", "reasoning", "alternatives"],
                        },
                    },
                    "sizing_assumptions": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "warnings": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Any sizing concerns or caveats.",
                    },
                },
                "required": ["workload_profile", "recommendations", "sizing_assumptions", "warnings"],
            },
        },
    },
]
