"""Auto-generated by _split.py — stakeholder tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "create_stakeholder_plan",
            "description": (
                "Create a structured stakeholder communication plan for a difficult architectural or organizational situation. "
                "Returns a situation summary, audience-specific talking points, objection handling scripts, and recommended actions. "
                "Call this when the user describes a challenging stakeholder situation, a difficult conversation, or needs help presenting a recommendation."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "situation_summary": {
                        "type": "string",
                        "description": "1-2 sentence summary of the core challenge and what success looks like.",
                    },
                    "audiences": {
                        "type": "array",
                        "description": "Distinct stakeholder audiences, each with tailored guidance.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string", "description": "Audience name/role, e.g. CFO, Engineering Team, Security Compliance Officer"},
                                "talking_points": {
                                    "type": "array",
                                    "items": {"type": "string"},
                                    "description": "3-5 concrete talking points framed for this audience's priorities.",
                                },
                                "objections_and_responses": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "objection": {"type": "string"},
                                            "response": {"type": "string"},
                                        },
                                        "required": ["objection", "response"],
                                    },
                                    "description": "Anticipated objections with concrete response scripts.",
                                },
                            },
                            "required": ["name", "talking_points", "objections_and_responses"],
                        },
                    },
                    "recommended_actions": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Concrete next actions to move the situation forward.",
                    },
                    "timeline": {
                        "type": "string",
                        "description": "Recommended timeline or sequencing for stakeholder conversations.",
                    },
                },
                "required": ["situation_summary", "audiences", "recommended_actions"],
            },
        },
    },
]
