"""Auto-generated by _split.py — troubleshoot tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "diagnose_issue",
            "description": (
                "Rank likely root causes for an Azure infrastructure issue with severity, "
                "blast radius, and affected services."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "symptom": {"type": "string", "description": "What the user is observing."},
                    "severity": {"type": "string", "enum": ["low", "medium", "high", "critical"]},
                    "blast_radius": {"type": "string", "description": "Scope of impact (single tenant, region, global)."},
                    "affected_services": {"type": "array", "items": {"type": "string"}},
                    "hypotheses": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "cause": {"type": "string"},
                                "likelihood": {"type": "string", "enum": ["high", "medium", "low"]},
                                "evidence_needed": {"type": "string"},
                                "rule_out_check": {"type": "string"},
                            },
                            "required": ["cause", "likelihood"],
                        },
                    },
                },
                "required": ["symptom", "severity", "hypotheses"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_kql_queries",
            "description": (
                "Emit targeted Azure Monitor / Log Analytics KQL queries for evidence gathering. "
                "Be specific about table names, time windows, and key columns."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "queries": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {"type": "string", "description": "Short descriptive name, e.g. 'API Gateway 5xx Errors'"},
                                "purpose": {"type": "string"},
                                "table": {"type": "string", "description": "AzureDiagnostics, ContainerLog, AppTraces, etc."},
                                "kql": {"type": "string"},
                                "time_window": {"type": "string", "description": "e.g. 'last 1h', 'last 24h'"},
                            },
                            "required": ["name", "kql"],
                        },
                    },
                },
                "required": ["queries"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "generate_remediation_runbook",
            "description": (
                "Step-by-step fix procedure with exact commands, expected outputs, and fallbacks. "
                "Include service-restart and downtime notes per step."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "steps": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "order": {"type": "integer"},
                                "action": {"type": "string"},
                                "command": {"type": "string", "description": "az / pwsh / kubectl invocation."},
                                "expected_output": {"type": "string"},
                                "fallback": {"type": "string"},
                                "causes_downtime": {"type": "boolean"},
                            },
                            "required": ["order", "action"],
                        },
                    },
                    "escalation_path": {"type": "string"},
                    "estimated_resolution_minutes": {"type": "integer"},
                },
                "required": ["steps"],
            },
        },
    },
]
