"""Auto-generated by _split.py — waf tool schemas."""

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "assess_waf_pillar",
            "description": (
                "Assess an architecture against one Well-Architected Framework pillar. "
                "Returns a score (1-5), key findings, and remediation recommendations. "
                "Call once per pillar for a full WAF assessment."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "pillar": {
                        "type": "string",
                        "enum": [
                            "reliability", "security", "cost",
                            "operational-excellence", "performance",
                        ],
                    },
                    "architecture_description": {
                        "type": "string",
                        "description": "Description of the architecture to assess.",
                    },
                    "score": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 5,
                        "description": "Pillar score: 1=critical gaps, 5=excellent.",
                    },
                    "findings": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Key findings for this pillar.",
                    },
                    "recommendations": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Prioritized remediation recommendations.",
                    },
                },
                "required": ["pillar", "architecture_description", "score", "findings", "recommendations"],
            },
        },
    },
]
